import React from 'react';
import { 
  LayoutDashboard, 
  PlusCircle, 
  Target, 
  CreditCard, 
  TrendingUp, 
  TrendingDown, 
  AlertTriangle,
  HelpCircle,
  Zap,
  CheckCircle2,
  AlertCircle,
  CalendarDays,
  Clock,
  ArrowRight,
  Copy,
  BarChart3,
  Filter,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Edit2,
  Trash2,
  MoreHorizontal,
  Camera,
  Loader2,
  X
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Add: PlusCircle,
  Plan: Target,
  Target: Target,
  Debts: CreditCard,
  Income: TrendingUp,
  Expense: TrendingDown,
  Burn: Zap,
  Alert: AlertTriangle,
  Check: CheckCircle2,
  Critical: AlertCircle,
  Calendar: CalendarDays,
  Clock: Clock,
  ArrowRight: ArrowRight,
  Copy: Copy,
  Reports: BarChart3,
  Filter: Filter,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  ChevronDown: ChevronDown,
  Edit: Edit2,
  Trash: Trash2,
  More: MoreHorizontal,
  Camera: Camera,
  Loader: Loader2,
  Close: X,
  Help: HelpCircle,
};
